"""Definition aller Bulk-Wissensquellen (Git, Archive.org, rsync)."""

# Git-Repositories (shallow clone, --depth 1)
GIT_SOURCES = [
    {
        "id": "arch-wiki",
        "name": "Arch Wiki",
        "url": "https://github.com/archlinux/archwiki.git",
        "subdir": "arch-wiki",
        "marker": "README.md",
    },
    {
        "id": "kubernetes-docs",
        "name": "Kubernetes Docs",
        "url": "https://github.com/kubernetes/website.git",
        "subdir": "official-docs/kubernetes",
        "marker": "content",
    },
    {
        "id": "python-docs",
        "name": "Python Dokumentation",
        "url": "https://github.com/python/cpython.git",
        "subdir": "official-docs/python",
        "marker": "Doc",
        "sparse": "Doc",
    },
    {
        "id": "rust-reference",
        "name": "Rust Reference",
        "url": "https://github.com/rust-lang/reference.git",
        "subdir": "official-docs/rust",
        "marker": "src",
    },
    {
        "id": "go-doc",
        "name": "Go Dokumentation",
        "url": "https://github.com/golang/go.git",
        "subdir": "official-docs/go",
        "marker": "doc",
        "sparse": "doc",
    },
    {
        "id": "nginx-docs",
        "name": "Nginx Docs",
        "url": "https://github.com/nginx/documentation.git",
        "subdir": "official-docs/nginx",
        "marker": "content",
    },
    {
        "id": "redis-docs",
        "name": "Redis Docs",
        "url": "https://github.com/redis/redis-doc.git",
        "subdir": "official-docs/redis",
        "marker": "commands",
    },
    {
        "id": "postgres-docs",
        "name": "PostgreSQL Docs",
        "url": "https://github.com/postgres/postgres.git",
        "subdir": "official-docs/postgresql",
        "marker": "doc",
        "sparse": "doc",
    },
    {
        "id": "docker-docs",
        "name": "Docker Docs",
        "url": "https://github.com/docker/docs.git",
        "subdir": "official-docs/docker",
        "marker": "content",
    },
    {
        "id": "terraform-docs",
        "name": "Terraform Docs",
        "url": "https://github.com/hashicorp/terraform.git",
        "subdir": "official-docs/terraform",
        "marker": "website",
        "sparse": "website/docs",
    },
    {
        "id": "owasp-cheatsheets",
        "name": "OWASP Cheat Sheets",
        "url": "https://github.com/OWASP/CheatSheetSeries.git",
        "subdir": "owasp/CheatSheetSeries",
        "marker": "cheatsheets",
    },
    {
        "id": "owasp-asvs",
        "name": "OWASP ASVS",
        "url": "https://github.com/OWASP/ASVS.git",
        "subdir": "owasp/ASVS",
        "marker": "4.0",
    },
    {
        "id": "owasp-wstg",
        "name": "OWASP WSTG",
        "url": "https://github.com/OWASP/wstg.git",
        "subdir": "owasp/wstg",
        "marker": "document",
    },
    {
        "id": "freebsd-doc",
        "name": "FreeBSD Handbook",
        "url": "https://github.com/freebsd/freebsd-doc.git",
        "subdir": "official-docs/freebsd",
        "marker": "documentation",
    },
    {
        "id": "ansible-docs",
        "name": "Ansible Docs",
        "url": "https://github.com/ansible/ansible-documentation.git",
        "subdir": "official-docs/ansible",
        "marker": "docs",
    },
    {
        "id": "git-scm-docs",
        "name": "Git SCM Book",
        "url": "https://github.com/git/git-scm.com.git",
        "subdir": "official-docs/git",
        "marker": "content",
    },
    # ─── Erweiterte Quellen ───
    {
        "id": "react-docs",
        "name": "React Docs",
        "url": "https://github.com/reactjs/react.dev.git",
        "subdir": "official-docs/react",
        "marker": "src",
    },
    {
        "id": "typescript-docs",
        "name": "TypeScript Handbook",
        "url": "https://github.com/microsoft/TypeScript-Handbook.git",
        "subdir": "official-docs/typescript",
        "marker": "pages",
    },
    {
        "id": "vue-docs",
        "name": "Vue.js Docs",
        "url": "https://github.com/vuejs/docs.git",
        "subdir": "official-docs/vue",
        "marker": "src",
    },
    {
        "id": "nextjs-docs",
        "name": "Next.js Docs",
        "url": "https://github.com/vercel/next.js.git",
        "subdir": "official-docs/nextjs",
        "marker": "docs",
        "sparse": "docs",
    },
    {
        "id": "nodejs-docs",
        "name": "Node.js Docs",
        "url": "https://github.com/nodejs/node.git",
        "subdir": "official-docs/nodejs",
        "marker": "doc",
        "sparse": "doc",
    },
    {
        "id": "webpack-docs",
        "name": "Webpack Docs",
        "url": "https://github.com/webpack/webpack.js.org.git",
        "subdir": "official-docs/webpack",
        "marker": "src",
    },
    {
        "id": "mysql-docs",
        "name": "MySQL Server Docs",
        "url": "https://github.com/mysql/mysql-server.git",
        "subdir": "official-docs/mysql",
        "marker": "Docs",
        "sparse": "Docs",
    },
    {
        "id": "mongodb-docs",
        "name": "MongoDB Manual",
        "url": "https://github.com/mongodb/docs.git",
        "subdir": "official-docs/mongodb",
        "marker": "source",
    },
    {
        "id": "elasticsearch-docs",
        "name": "Elasticsearch Docs",
        "url": "https://github.com/elastic/elasticsearch.git",
        "subdir": "official-docs/elasticsearch",
        "marker": "docs",
        "sparse": "docs",
    },
    {
        "id": "prometheus-docs",
        "name": "Prometheus Docs",
        "url": "https://github.com/prometheus/docs.git",
        "subdir": "official-docs/prometheus",
        "marker": "content",
    },
    {
        "id": "grafana-docs",
        "name": "Grafana Docs",
        "url": "https://github.com/grafana/grafana.git",
        "subdir": "official-docs/grafana",
        "marker": "docs",
        "sparse": "docs",
    },
    {
        "id": "django-docs",
        "name": "Django Docs",
        "url": "https://github.com/django/django.git",
        "subdir": "official-docs/django",
        "marker": "docs",
        "sparse": "docs",
    },
    {
        "id": "flask-docs",
        "name": "Flask Docs",
        "url": "https://github.com/pallets/flask.git",
        "subdir": "official-docs/flask",
        "marker": "docs",
        "sparse": "docs",
    },
    {
        "id": "spring-docs",
        "name": "Spring Framework Docs",
        "url": "https://github.com/spring-projects/spring-framework.git",
        "subdir": "official-docs/spring",
        "marker": "src",
        "sparse": "framework-docs/src",
    },
    {
        "id": "linux-kernel-docs",
        "name": "Linux Kernel Docs",
        "url": "https://github.com/torvalds/linux.git",
        "subdir": "official-docs/linux-kernel",
        "marker": "Documentation",
        "sparse": "Documentation",
    },
    {
        "id": "systemdesign-primer",
        "name": "System Design Primer",
        "url": "https://github.com/donnemartin/system-design-primer.git",
        "subdir": "official-docs/system-design",
        "marker": "README.md",
    },
    {
        "id": "coding-interview",
        "name": "Coding Interview University",
        "url": "https://github.com/jwasham/coding-interview-university.git",
        "subdir": "official-docs/coding-interview",
        "marker": "README.md",
    },
    {
        "id": "rust-book",
        "name": "Rust Book",
        "url": "https://github.com/rust-lang/book.git",
        "subdir": "official-docs/rust-book",
        "marker": "src",
    },
    {
        "id": "svelte-docs",
        "name": "Svelte Docs",
        "url": "https://github.com/sveltejs/svelte.git",
        "subdir": "official-docs/svelte",
        "marker": "documentation",
        "sparse": "documentation",
    },
    {
        "id": "tailwind-docs",
        "name": "Tailwind CSS Docs",
        "url": "https://github.com/tailwindlabs/tailwindcss.com.git",
        "subdir": "official-docs/tailwindcss",
        "marker": "src",
    },
    {
        "id": "owasp-top10",
        "name": "OWASP Top 10",
        "url": "https://github.com/OWASP/Top10.git",
        "subdir": "owasp/Top10",
        "marker": "2021",
    },
    {
        "id": "aws-docs",
        "name": "AWS Well-Architected",
        "url": "https://github.com/awslabs/aws-well-architected-labs.git",
        "subdir": "official-docs/aws",
        "marker": "content",
    },
]

# Stack Exchange Archive.org (7z → XML Posts)
# https://archive.org/details/stackexchange
STACKEXCHANGE_DUMPS = [
    {
        "name": "Stack Overflow",
        "site": "stackoverflow.com",
        "file": "stackoverflow.com-Posts.7z",
        "url": "https://archive.org/download/stackexchange/stackoverflow.com-Posts.7z",
        "size": "~15 GB",
    },
    {
        "name": "Server Fault",
        "site": "serverfault.com",
        "file": "serverfault.com.7z",
        "url": "https://archive.org/download/stackexchange/serverfault.com.7z",
        "size": "~1 GB",
    },
    {
        "name": "Super User",
        "site": "superuser.com",
        "file": "superuser.com.7z",
        "url": "https://archive.org/download/stackexchange/superuser.com.7z",
        "size": "~2 GB",
    },
    {
        "name": "Security SE",
        "site": "security.stackexchange.com",
        "file": "security.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/security.stackexchange.com.7z",
        "size": "~500 MB",
    },
    {
        "name": "Ask Ubuntu",
        "site": "askubuntu.com",
        "file": "askubuntu.com.7z",
        "url": "https://archive.org/download/stackexchange/askubuntu.com.7z",
        "size": "~1.5 GB",
    },
    {
        "name": "Unix SE",
        "site": "unix.stackexchange.com",
        "file": "unix.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/unix.stackexchange.com.7z",
        "size": "~1 GB",
    },
    {
        "name": "Software Engineering SE",
        "site": "softwareengineering.stackexchange.com",
        "file": "softwareengineering.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/softwareengineering.stackexchange.com.7z",
        "size": "~400 MB",
    },
    {
        "name": "DBA SE",
        "site": "dba.stackexchange.com",
        "file": "dba.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/dba.stackexchange.com.7z",
        "size": "~400 MB",
    },
    {
        "name": "Code Review SE",
        "site": "codereview.stackexchange.com",
        "file": "codereview.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/codereview.stackexchange.com.7z",
        "size": "~300 MB",
    },
    {
        "name": "DevOps SE",
        "site": "devops.stackexchange.com",
        "file": "devops.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/devops.stackexchange.com.7z",
        "size": "~50 MB",
    },
    {
        "name": "Raspberry Pi SE",
        "site": "raspberrypi.stackexchange.com",
        "file": "raspberrypi.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/raspberrypi.stackexchange.com.7z",
        "size": "~100 MB",
    },
    {
        "name": "Network Engineering SE",
        "site": "networkengineering.stackexchange.com",
        "file": "networkengineering.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/networkengineering.stackexchange.com.7z",
        "size": "~50 MB",
    },
    {
        "name": "Data Science SE",
        "site": "datascience.stackexchange.com",
        "file": "datascience.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/datascience.stackexchange.com.7z",
        "size": "~100 MB",
    },
    {
        "name": "AI SE",
        "site": "ai.stackexchange.com",
        "file": "ai.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/ai.stackexchange.com.7z",
        "size": "~50 MB",
    },
    {
        "name": "Webmasters SE",
        "site": "webmasters.stackexchange.com",
        "file": "webmasters.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/webmasters.stackexchange.com.7z",
        "size": "~100 MB",
    },
    {
        "name": "Ethereum SE",
        "site": "ethereum.stackexchange.com",
        "file": "ethereum.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/ethereum.stackexchange.com.7z",
        "size": "~100 MB",
    },
    {
        "name": "WordPress SE",
        "site": "wordpress.stackexchange.com",
        "file": "wordpress.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/wordpress.stackexchange.com.7z",
        "size": "~400 MB",
    },
    {
        "name": "Arduino SE",
        "site": "arduino.stackexchange.com",
        "file": "arduino.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/arduino.stackexchange.com.7z",
        "size": "~50 MB",
    },
    {
        "name": "Electrical Engineering SE",
        "site": "electronics.stackexchange.com",
        "file": "electronics.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/electronics.stackexchange.com.7z",
        "size": "~400 MB",
    },
]

STACKEXCHANGE_UNIVERSAL = [
    {
        "name": "Physics SE",
        "site": "physics.stackexchange.com",
        "file": "physics.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/physics.stackexchange.com.7z",
        "size": "~800 MB",
    },
    {
        "name": "Math SE",
        "site": "math.stackexchange.com",
        "file": "math.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/math.stackexchange.com.7z",
        "size": "~5 GB",
    },
    {
        "name": "Biology SE",
        "site": "biology.stackexchange.com",
        "file": "biology.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/biology.stackexchange.com.7z",
        "size": "~200 MB",
    },
    {
        "name": "Chemistry SE",
        "site": "chemistry.stackexchange.com",
        "file": "chemistry.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/chemistry.stackexchange.com.7z",
        "size": "~300 MB",
    },
    {
        "name": "History SE",
        "site": "history.stackexchange.com",
        "file": "history.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/history.stackexchange.com.7z",
        "size": "~150 MB",
    },
    {
        "name": "Law SE",
        "site": "law.stackexchange.com",
        "file": "law.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/law.stackexchange.com.7z",
        "size": "~200 MB",
    },
    {
        "name": "Philosophy SE",
        "site": "philosophy.stackexchange.com",
        "file": "philosophy.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/philosophy.stackexchange.com.7z",
        "size": "~100 MB",
    },
    {
        "name": "Economics SE",
        "site": "economics.stackexchange.com",
        "file": "economics.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/economics.stackexchange.com.7z",
        "size": "~100 MB",
    },
    {
        "name": "English Language SE",
        "site": "english.stackexchange.com",
        "file": "english.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/english.stackexchange.com.7z",
        "size": "~600 MB",
    },
    {
        "name": "Skeptics SE",
        "site": "skeptics.stackexchange.com",
        "file": "skeptics.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/skeptics.stackexchange.com.7z",
        "size": "~100 MB",
    },
    {
        "name": "Music SE",
        "site": "music.stackexchange.com",
        "file": "music.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/music.stackexchange.com.7z",
        "size": "~100 MB",
    },
    {
        "name": "Cooking SE",
        "site": "cooking.stackexchange.com",
        "file": "cooking.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/cooking.stackexchange.com.7z",
        "size": "~100 MB",
    },
    {
        "name": "Travel SE",
        "site": "travel.stackexchange.com",
        "file": "travel.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/travel.stackexchange.com.7z",
        "size": "~200 MB",
    },
    {
        "name": "Health SE",
        "site": "health.stackexchange.com",
        "file": "health.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/health.stackexchange.com.7z",
        "size": "~50 MB",
    },
    {
        "name": "Worldbuilding SE",
        "site": "worldbuilding.stackexchange.com",
        "file": "worldbuilding.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/worldbuilding.stackexchange.com.7z",
        "size": "~300 MB",
    },
    {
        "name": "Earth Science SE",
        "site": "earthscience.stackexchange.com",
        "file": "earthscience.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/earthscience.stackexchange.com.7z",
        "size": "~50 MB",
    },
    {
        "name": "Space Exploration SE",
        "site": "space.stackexchange.com",
        "file": "space.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/space.stackexchange.com.7z",
        "size": "~100 MB",
    },
    {
        "name": "Linguistics SE",
        "site": "linguistics.stackexchange.com",
        "file": "linguistics.stackexchange.com.7z",
        "url": "https://archive.org/download/stackexchange/linguistics.stackexchange.com.7z",
        "size": "~50 MB",
    },
]

GIT_SOURCES_UNIVERSAL = [
    {
        "id": "openstax-bio",
        "name": "OpenStax Biology",
        "url": "https://github.com/openstax/osbooks-biology-bundle.git",
        "subdir": "textbooks/biology",
        "marker": "modules",
    },
    {
        "id": "openstax-physics",
        "name": "OpenStax Physics",
        "url": "https://github.com/openstax/osbooks-university-physics-bundle.git",
        "subdir": "textbooks/physics",
        "marker": "modules",
    },
    {
        "id": "openstax-chem",
        "name": "OpenStax Chemistry",
        "url": "https://github.com/openstax/osbooks-chemistry-bundle.git",
        "subdir": "textbooks/chemistry",
        "marker": "modules",
    },
    {
        "id": "openstax-econ",
        "name": "OpenStax Economics",
        "url": "https://github.com/openstax/osbooks-principles-economics-bundle.git",
        "subdir": "textbooks/economics",
        "marker": "modules",
    },
    {
        "id": "openstax-history",
        "name": "OpenStax World History",
        "url": "https://github.com/openstax/osbooks-world-history.git",
        "subdir": "textbooks/world-history",
        "marker": "modules",
    },
    {
        "id": "openstax-anatomy",
        "name": "OpenStax Anatomy & Physiology",
        "url": "https://github.com/openstax/osbooks-anatomy-physiology.git",
        "subdir": "textbooks/anatomy",
        "marker": "modules",
    },
    {
        "id": "openstax-astronomy",
        "name": "OpenStax Astronomy",
        "url": "https://github.com/openstax/osbooks-astronomy.git",
        "subdir": "textbooks/astronomy",
        "marker": "modules",
    },
    {
        "id": "openstax-psychology",
        "name": "OpenStax Psychology",
        "url": "https://github.com/openstax/osbooks-psychology.git",
        "subdir": "textbooks/psychology",
        "marker": "modules",
    },
    {
        "id": "openstax-sociology",
        "name": "OpenStax Sociology",
        "url": "https://github.com/openstax/osbooks-introduction-sociology.git",
        "subdir": "textbooks/sociology",
        "marker": "modules",
    },
]

# IETF Internet-Drafts (zusätzlich zu RFCs)
IETF_DRAFTS_URL = "https://www.ietf.org/archive/id/draft-"
IETF_DRAFTS_INDEX = "https://www.ietf.org/archive/id/"

